name: cache

on:
  workflow_dispatch:

jobs:
  node-npm-depencies-caching:
    name: Setup-node npm (Node ${{ matrix.node-version}}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - uses: actions/setup-node@v3
      - name: Setup Node
        uses: ./
        with:
           node-version: 18
           cache: 'npm'
           cache-dependency-path: 'package.json'
           check-latest: true
      - name: Install dependencies
        run: npm install
          
  node-pnpm-depencies-caching:
    name: local cache npm (Node ${{ matrix.node-version}}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/cache@v3
      - name: Setup Node
        uses: ./
        key: ${{ runner.os }}-${{ matrix.node-version }}-9.8.0-npmcache-${{ hashFiles('**/package-lock.json') }}
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'yarn.lock'
          check-latest: true
      - name: Install dependencies
        run: npm install
     
