name: test ubuntu for node16

on:
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Node.js 16.20.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.2

      - name: Set up Node.js 14 (or any other version)
        uses: actions/setup-node@v3
        with:
          node-version: 20
