
name: Tests macos

on:
  workflow_dispatch :


jobs :

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13-arm64
            platform: darwin
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check runner architecture
        run: uname -m
      - shell: pwsh
        run: echo "target=${{ matrix.platform }}-${{ matrix.arch }}" >> $env:GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          architecture: ${{ matrix.arch }}
          cache: 'npm'
